### PR TITLE
Supported for django 2.0

### PR DESCRIPTION
**Pull request by agusmakmun**
- fixed `on_delete=models.CASCADE` that required for Django>=2.0
- fixed: 'bool' object is not callable is_authenticated

### CODE REVIEW

**Comment by dbanck** [comment]
Thanks for your PR! :star2:

Would you mind updating the `tox.ini` and add a new env for Django 2.0? I think we can also remove the `py33-django18` env.

**Comment by agusmakmun** [comment]
@dbanck welldone... :+1:

**Comment by dbanck** [comment]
Thanks, for your update!

When adding or removing a tox env, you also need to update the `.travis.yml` accordingly, so those new tests are being run on travis. I've updated the PR to reflect this.

If all tests are green now, we can merge this :)

**Comment by dbanck** [comment]
Thanks again. I'll publish a new release to pip.

**Comment by dbanck** [comment]
New Release: https://pypi.python.org/pypi/django-updown/1.1.0

**Pull request merged**
