### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by snahor**
`md5` requires an encoded object

### CODE REVIEW

**Comment by dbanck** [comment]
Thanks for your pull request.

Do you mind fixing the Travis CI integration?

**Comment by snahor** [comment]
Sure, no problem.

**Comment by dbanck** [comment]
Why did you remove all Python versions except for 3.4? It still needs to stay compatible with Python 2 ;)

**Comment by snahor** [comment]
It's included in tox.ini.

**Comment by passy** [comment]
It would be good to move away from MD5 in general. Not part of this PR, but there's really no excuse to use it for anything these days.

**Comment by dbanck** [comment]
Python 3 support and many other changes are finally happening. I'm closing this PR, thanks for your input.

**Pull request closed without merging**
